### ISSUE TITLE
Při zadání MMMMM program spadne

### ISSUE THREAD

**Issue by xtompok** [hofrajtm/zkouska#4]

**Comment by hofrajtm** [comment]
Zkoušel jsem a pracuje správně, respektive vypíše chybu 'Není možné, aby se v zadaném čísle opakovaly symboly I, V, X, L, C, D a M více než třikrát v řadě za sebou.', což odpovídá pravidlům, ze kterých jsem vycházel. Nezadával jsi tuto vstupní hodnotu při převodu z arabských na římské?
